### ISSUE TITLE
Extension airdcpp-release-validator has exited immediately after startup

### ISSUE THREAD

**Issue by bobo-j** [airdcpp-web/airdcpp-release-validator#16]
Here is the error log from 2021.01.04, 11:13:59

/media/boris/Archive/airdcpp-webclient_2.11b81_webui_2.11b3/config/extensions/airdcpp-release-validator/package/dist/webpack:/airdcpp-release-validator/node_modules/airdcpp-extension/dist-es/utils.js:13
    osVersion: osVersion(),
               ^
TypeError: (0 , F.version) is not a function
    at ManagedExtension (/media/boris/Archive/airdcpp-webclient_2.11b81_webui_2.11b3/config/extensions/airdcpp-release-validator/package/dist/webpack:/airdcpp-release-validator/node_modules/airdcpp-extension/dist-es/utils.js:13:16)
    at Module.call (/media/boris/Archive/airdcpp-webclient_2.11b81_webui_2.11b3/config/extensions/airdcpp-release-validator/package/dist/webpack:/airdcpp-release-validator/src/index.ts:13:1)
    at __webpack_require__ (/media/boris/Archive/airdcpp-webclient_2.11b81_webui_2.11b3/config/extensions/airdcpp-release-validator/package/dist/webpack:/airdcpp-release-validator/webpack/bootstrap:18:32)
    at /media/boris/Archive/airdcpp-webclient_2.11b81_webui_2.11b3/config/extensions/airdcpp-release-validator/package/dist/webpack:/airdcpp-release-validator/webpack/startup:4:8
    at factory (/media/boris/Archive/airdcpp-webclient_2.11b81_webui_2.11b3/config/extensions/airdcpp-release-validator/package/dist/main.js:1:230465)
    at e.8926.e.exports.n (/media/boris/Archive/airdcpp-webclient_2.11b81_webui_2.11b3/config/extensions/airdcpp-release-validator/package/dist/webpack:/airdcpp-release-validator/webpack/universalModuleDefinition:3:20)
    at Object.<anonymous> (/media/boris/Archive/airdcpp-webclient_2.11b81_webui_2.11b3/config/extensions/airdcpp-release-validator/package/dist/webpack:/airdcpp-release-validator/webpack/universalModuleDefinition:1:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

I use: Linux Mint 19.3 Cinnamon, Cinnamon Version 4.4.8, Linux Kernel 4.15.0-128-generic

**Comment by maksis** [comment]
What's you node version? `node -v`

**Comment by bobo-j** [comment]
v8.10.0

**Comment by maksis** [comment]
I'll publish fixed versions of the extensions in a while

**Comment by bobo-j** [comment]
I guess the errors with the other extensions are due to the same problem, because when I look at the logs they are almost the same. Whether to publish them or wait?

**Comment by maksis** [comment]
It's the same issue in all extensions that prevents them from being started with older node versions

**Comment by maksis** [comment]
Please try the latest version of `airdcpp-share-monitor`. If it's working fine, I'll update other extensions tomorrow.

**Comment by bobo-j** [comment]
Yes, it's working! -> airdcpp-share-monitor v1.1.2

**Comment by maksis** [comment]
All extensions have now been updated
